// AI Player Companion for EaglerForge / EaglercraftX 1.8
// v3.2 — natural-language agent tasks, pet mode, mining, defense, and autonomous mode
// A true second multiplayer player requires server/entity APIs. This mod does not fake one.

ModAPI.meta.title("AI Player Companion");
ModAPI.meta.version("3.2");
ModAPI.meta.description("AI companion with chat, visible HUD avatar, follow state, and safe build plans.");
ModAPI.meta.credits("BYOK OpenAI-compatible API support");
ModAPI.require("player");
ModAPI.require("world");

const STORAGE_KEY = "eagler_ai_player_config_v2";
const DEFAULT_PROMPT = `You are AI Buddy, a friendly Minecraft 1.8 companion.
Keep replies short and useful. You may include at most one action tag:
[FOLLOW], [STOP], [JUMP], [SAY:hello], [BUILD:house], [BUILD:tower], [BUILD:bridge], [MINE:tunnel], [DEFEND], [AUTO], [HALT], or [TP].
Never claim blocks were placed unless the client confirms it. If building is unavailable, explain that a build plan was prepared instead.`;
let config = { apiKey:"", baseUrl:"https://api.openai.com/v1", model:"gpt-4o-mini", systemPrompt:DEFAULT_PROMPT, companionName:"AI Buddy" };
try { const saved=localStorage.getItem(STORAGE_KEY); if(saved) Object.assign(config,JSON.parse(saved)); } catch(e) {}

let following=false, conversation=[], buildQueue=[], lastBuildReport="No build has been requested.", companionEl=null, statusEl=null, lastTick=0;
let mining=false, defending=false, autonomous=false, agentMode=false, petMode=false, petEntity=null;
function chat(msg){ModAPI.displayToChat({msg:"§d[AI Buddy] §f"+String(msg)});}
function saveConfig(){localStorage.setItem(STORAGE_KEY,JSON.stringify(config));}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#39;"}[c]));}
function updateCompanion(text,mood){if(!companionEl)return;companionEl.querySelector(".aip-name").textContent=config.companionName;companionEl.querySelector(".aip-face").textContent=mood==="happy"?"◕‿◕":mood==="thinking"?"◔‿◔":"•‿•";companionEl.querySelector(".aip-text").textContent=text;if(statusEl)statusEl.textContent=following?"FOLLOWING":buildQueue.length?"BUILDING":"READY";}
function createCompanion(){if(companionEl||!document.body)return;companionEl=document.createElement("div");companionEl.id="ai-player-companion";companionEl.innerHTML='<div class="aip-avatar"><div class="aip-face">•‿•</div></div><div class="aip-card"><b class="aip-name"></b><span class="aip-status" id="aip-status">READY</span><div class="aip-text">Loaded — type .ai help</div></div>';const style=document.createElement("style");style.textContent='#ai-player-companion{position:fixed;right:18px;bottom:18px;z-index:2147483647;display:flex;align-items:flex-end;gap:8px;font:13px Arial,sans-serif;color:#fff;pointer-events:none;filter:drop-shadow(0 3px 5px #000)}#ai-player-companion .aip-avatar{width:54px;height:68px;background:linear-gradient(#6ed0ff 0 42%,#3175d5 42% 70%,#29314b 70%);border:2px solid #fff;border-radius:8px 8px 4px 4px;display:grid;place-items:center}.aip-face{background:#18202c;color:#9ff;padding:4px 2px;border-radius:3px;font-size:12px}.aip-card{max-width:270px;background:rgba(18,18,28,.94);border:1px solid #c27cff;border-radius:8px;padding:8px 10px}.aip-name{color:#df9aff}.aip-status{float:right;margin-left:10px;font-size:10px;color:#8cffb0}.aip-text{margin-top:4px;line-height:1.3}';document.head.appendChild(style);document.body.appendChild(companionEl);statusEl=companionEl.querySelector("#aip-status");updateCompanion("Loaded — type .ai help","happy");}

ModAPI.meta.config(()=>{const gui=document.createElement("div");gui.style.cssText="position:fixed;inset:0;z-index:2147483647;background:#111;color:#eee;font:14px Arial;padding:22px;overflow:auto";gui.innerHTML=`<h2>AI Player Companion 2.0</h2><label>API key<br><input id="aip-key" type="password" style="width:100%;padding:8px" value="${esc(config.apiKey)}"></label><br><label>Base URL<br><input id="aip-url" style="width:100%;padding:8px" value="${esc(config.baseUrl)}"></label><br><label>Model<br><input id="aip-model" style="width:100%;padding:8px" value="${esc(config.model)}"></label><br><label>Companion name<br><input id="aip-name" style="width:100%;padding:8px" value="${esc(config.companionName)}"></label><br><label>System prompt<br><textarea id="aip-prompt" rows="7" style="width:100%;padding:8px">${esc(config.systemPrompt)}</textarea></label><br><button id="aip-save">Save</button> <button id="aip-close">Close</button><p>Never share an API key or commit one to GitHub. Browser CORS must allow this page.</p>`;document.body.appendChild(gui);gui.querySelector("#aip-save").onclick=()=>{config.apiKey=gui.querySelector("#aip-key").value.trim();config.baseUrl=gui.querySelector("#aip-url").value.trim().replace(/\/$/,"");config.model=gui.querySelector("#aip-model").value.trim();config.companionName=gui.querySelector("#aip-name").value.trim()||"AI Buddy";config.systemPrompt=gui.querySelector("#aip-prompt").value;saveConfig();updateCompanion("Settings saved!","happy");chat("Settings saved!");gui.remove();};gui.querySelector("#aip-close").onclick=()=>gui.remove();});

async function callAI(userMessage){if(!config.apiKey){chat("No API key set. Open Mods → AI Player Companion → Config.");updateCompanion("Add your API key in Config","thinking");return null;}conversation.push({role:"user",content:userMessage});if(conversation.length>8)conversation=conversation.slice(-6);try{const res=await fetch(config.baseUrl+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+config.apiKey},body:JSON.stringify({model:config.model,messages:[{role:"system",content:config.systemPrompt},...conversation],temperature:.5,max_tokens:180})});if(!res.ok){chat("API error: "+res.status);return null;}const data=await res.json();const reply=data.choices?.[0]?.message?.content?.trim()||"I have nothing to say yet.";conversation.push({role:"assistant",content:reply});return reply;}catch(e){chat("Network/CORS error: "+e.message);updateCompanion("API connection failed","thinking");return null;}}
function setFollowing(value){following=!!value;updateCompanion(following?"I’ll stay close to you.":"I stopped following.","happy");chat(following?"Following mode ON.":"Following mode OFF.");}
function executeActions(text){let clean=text;if(/\[FOLLOW\]/i.test(text)){setFollowing(true);clean=clean.replace(/\[FOLLOW\]/gi,"");}if(/\[STOP\]/i.test(text)){setFollowing(false);clean=clean.replace(/\[STOP\]/gi,"");}if(/\[JUMP\]/i.test(text)){try{ModAPI.player.motionY=.42;ModAPI.player.reload();}catch(e){}clean=clean.replace(/\[JUMP\]/gi,"");}const say=text.match(/\[SAY:(.+?)\]/i);if(say){try{ModAPI.player.sendChatMessage(ModAPI.util.str(say[1].trim()));}catch(e){}clean=clean.replace(/\[SAY:.+?\]/gi,"");}const build=text.match(/\[BUILD:(house|tower|bridge)\]/i);if(build){requestBuild(build[1].toLowerCase());clean=clean.replace(/\[BUILD:(house|tower|bridge)\]/gi,"");}if(/\[MINE:(tunnel|ore)\]/i.test(text)){requestMine(text.match(/\[MINE:(tunnel|ore)\]/i)[1].toLowerCase());clean=clean.replace(/\[MINE:(tunnel|ore)\]/gi,"");}if(/\[DEFEND\]/i.test(text)){startDefense();clean=clean.replace(/\[DEFEND\]/gi,"");}if(/\[AUTO\]/i.test(text)){startAuto();clean=clean.replace(/\[AUTO\]/gi,"");}if(/\[HALT\]/i.test(text)){stopTasks();clean=clean.replace(/\[HALT\]/gi,"");}if(/\[TP\]/i.test(text)){chat("Teleport is disabled in v3 for safety and server compatibility.");clean=clean.replace(/\[TP\]/gi,"");}return clean.trim();}
function blockId(name){return({dirt:"dirt",stone:"stone",cobble:"cobblestone",wood:"planks",planks:"planks",glass:"glass",sand:"sand"}[name]||"dirt");}
function stopTasks(){mining=false;defending=false;autonomous=false;agentMode=false;following=false;buildQueue=[];chat("All AI tasks stopped.");updateCompanion("Stopped — waiting for your command.","happy");}
function findPet(){const w=ModAPI.world;const p=ModAPI.player;if(!w||!p||typeof w.getEntities!=="function"){chat("This build does not expose existing animal entities.");return null;}try{const list=w.getEntities()||[];const animals=list.filter(e=>{const n=String(e.name||e.type||e.entityType||"").toLowerCase();return /cow|pig|sheep|chicken|wolf|cat|ocelot|rabbit|horse/.test(n);});if(!animals.length){chat("No nearby animal was exposed to the ModAPI.");return null;}return animals[0];}catch(e){chat("Animal lookup failed in this build.");return null;}}
function startPet(){petEntity=findPet();if(!petEntity)return;petMode=true;chat("Pet mode ON — I will try to guide the nearest animal toward you.");}
function stopPet(){petMode=false;petEntity=null;chat("Pet mode OFF.");}
function guidePet(){if(!petMode)return;if(!petEntity||!ModAPI.player){petEntity=findPet();if(!petEntity)return;}try{const p=ModAPI.player,e=petEntity;const dx=p.x-e.x,dz=p.z-e.z,dist=Math.sqrt(dx*dx+dz*dz);if(dist>3){e.motionX=(dx/dist)*.08;e.motionZ=(dz/dist)*.08;if(typeof e.reload==="function")e.reload();}else{e.motionX=0;e.motionZ=0;if(typeof e.reload==="function")e.reload();}}catch(err){petMode=false;petEntity=null;chat("This build exposes animals as read-only, so pet control stopped.");}}

function requestMine(kind){const p=ModAPI.player;if(!p){chat("I cannot see your player yet.");return;}kind=kind||"tunnel";const x=Math.floor(p.x),y=Math.floor(p.y),z=Math.floor(p.z);buildQueue=[];for(let i=1;i<=12;i++){buildQueue.push({x:x+i,y:y,z:z,action:"mine",target:kind});if(i%4===0)buildQueue.push({x:x+i,y:y+1,z:z,action:"mine",target:kind});}mining=true;defending=false;lastBuildReport=`Prepared a ${kind} mining route with ${buildQueue.length} steps.`;updateCompanion(lastBuildReport,"happy");chat(lastBuildReport+" Actual mining depends on the exposed world API.");}
function startDefense(){defending=true;mining=false;updateCompanion("Watching for nearby threats.","happy");chat("Defense mode ON. I will only use exposed local combat APIs and will not bypass server rules.");}
function startAuto(){autonomous=true;following=true;defending=true;chat("AUTO mode ON: follow, defend, mine, and build plans will run locally. Type .ai halt to stop.");updateCompanion("Auto mode active.","happy");}
function startAgentTask(task){if(!task){chat("Usage: .ai agent <what you want me to do>");return;}agentMode=true;startAuto();chat("Agent task started: "+task);updateCompanion("Agent is planning…","thinking");callAI("You are now an in-game task agent. Execute this task using only supported action tags and do not claim unsupported actions succeeded: "+task).then(reply=>{if(!reply)return;const cleaned=executeActions(reply);if(cleaned){chat(cleaned);updateCompanion(cleaned,"happy");}});}

function tryMineOne(){if(!buildQueue.length){mining=false;if(autonomous)requestMine("tunnel");return;}const q=buildQueue.shift(),w=ModAPI.world;try{if(w&&typeof w.breakBlock==="function"){w.breakBlock(q.x,q.y,q.z);return;}if(w&&typeof w.destroyBlock==="function"){w.destroyBlock(q.x,q.y,q.z);return;}buildQueue=[];mining=false;chat("Mining plan ready, but this build does not expose a block-breaking API.");updateCompanion("Mining API unavailable — plan ready.","thinking");}catch(e){mining=false;chat("Mining stopped: the world API rejected the action.");}}
function tryDefend(){const w=ModAPI.world;if(!w)return;try{const entities=typeof w.getEntities==="function"?w.getEntities():[];const hostile=entities.find(e=>{const n=String(e.name||e.type||e.entityType||"").toLowerCase();return /zombie|skeleton|creeper|spider|hostile|mob/.test(n);});if(!hostile)return;const p=ModAPI.player;if(p&&typeof p.attackEntity==="function")p.attackEntity(hostile);else if(typeof w.attackEntity==="function")w.attackEntity(p,hostile);else updateCompanion("Threat spotted — combat API unavailable.","thinking");}catch(e){}}
function runAuto(){if(!autonomous)return;if(!mining&&!buildQueue.length&&Math.random()<.04)requestBuild("house");if(!mining&&Math.random()<.10)requestMine("tunnel");}

function requestBuild(kind){const p=ModAPI.player;if(!p){chat("I cannot see your player yet.");return;}const x=Math.floor(p.x),y=Math.floor(p.y),z=Math.floor(p.z);buildQueue=[];if(kind==="tower"){for(let yy=0;yy<5;yy++)for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++)if(Math.abs(dx)===1||Math.abs(dz)===1)buildQueue.push({x:x+dx,y:y+yy,z:z+dz,b:"stone"});}else if(kind==="bridge"){for(let i=1;i<=8;i++)buildQueue.push({x:x+i,y:y-1,z:z,b:"wood"});}else{for(let dx=-3;dx<=3;dx++)for(let dz=-3;dz<=3;dz++)if(Math.abs(dx)===3||Math.abs(dz)===3)for(let yy=0;yy<3;yy++)buildQueue.push({x:x+dx,y:y+yy,z:z+dz,b:"wood"});for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)buildQueue.push({x:x+dx,y:y+3,z:z+dz,b:"wood"});}lastBuildReport=`Prepared ${buildQueue.length} blocks for a ${kind}.`;updateCompanion(lastBuildReport,"happy");chat(lastBuildReport+" Build execution depends on the exposed world API.");}
function tryPlaceOne(){if(!buildQueue.length)return;const q=buildQueue.shift(),w=ModAPI.world;try{if(w&&typeof w.setBlockState==="function"){w.setBlockState(q.x,q.y,q.z,blockId(q.b));return;}if(w&&typeof w.setBlock==="function"){w.setBlock(q.x,q.y,q.z,blockId(q.b));return;}buildQueue=[];lastBuildReport="Build plan ready, but this build does not expose a client block-placement API.";updateCompanion(lastBuildReport,"thinking");chat(lastBuildReport);}catch(e){buildQueue=[];chat("Build stopped: the world API rejected placement.");}}

ModAPI.addEventListener("sendchatmessage",e=>{const msg=e.message.trim();if(!msg.toLowerCase().startsWith(".ai"))return;e.preventDefault=true;const low=msg.toLowerCase();if(low===".ai"||low===".ai help"){chat("Commands: .ai <message>, .ai agent <task>, .ai follow, .ai stop, .ai pet, .ai pet stop, .ai mine [tunnel|ore], .ai defend, .ai auto, .ai halt, .ai build house|tower|bridge, .ai clear, .ai status");return;}if(low.startsWith(".ai agent ")){startAgentTask(msg.slice(10).trim());return;}if(low===".ai agent"){chat("Usage: .ai agent <what you want me to do>");return;}if(low===".ai follow"){setFollowing(true);return;}if(low===".ai stop"){setFollowing(false);return;}if(low===".ai halt"||low===".ai stop all"){stopTasks();return;}if(low===".ai defend"){startDefense();return;}if(low===".ai pet"||low===".ai pet follow"){startPet();return;}if(low===".ai pet stop"){stopPet();return;}if(low===".ai attack"){startDefense();return;}if(low===".ai mine"||low.startsWith(".ai mine ")){requestMine(low.slice(8).trim()||"tunnel");return;}if(low===".ai auto"){startAuto();return;}if(low===".ai clear"){conversation=[];chat("Conversation cleared.");return;}if(low.startsWith(".ai build ")){requestBuild(low.slice(10).trim());return;}if(low===".ai status"){chat(`Model: ${config.model} | Key: ${config.apiKey?"set":"NO"} | Follow: ${following?"on":"off"} | Mine: ${mining?"on":"off"} | Defend: ${defending?"on":"off"} | Auto: ${autonomous?"on":"off"} | Agent: ${agentMode?"on":"off"} | ${lastBuildReport}`);return;}const prompt=msg.slice(3).trim();if(!prompt)return;chat("Thinking…");updateCompanion("Thinking…","thinking");callAI(prompt).then(reply=>{if(!reply)return;const cleaned=executeActions(reply);if(cleaned){chat(cleaned);updateCompanion(cleaned,"happy");}});});
ModAPI.addEventListener("update",()=>{const now=Date.now();if(now-lastTick<100)return;lastTick=now;try{if(mining)tryMineOne();else if(buildQueue.length)tryPlaceOne();if(defending)tryDefend();guidePet();runAuto();if(following&&ModAPI.player)updateCompanion(autonomous?"Auto mode: staying with you.":"I’m staying with you.","happy");}catch(e){}});
ModAPI.addEventListener("load",()=>setTimeout(()=>{chat("Loaded v3.1 Pet Mode! Type .ai help. Pet mode controls an existing nearby animal when this build allows it.");},1200));
console.log("[AI Player Companion] v3.2 loaded");
